codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default: off
      application:
        flags: application
      modules:
        flags: modules
      system:
        flags: system

flags:
  application:
    paths:
      - application/
  modules:
    paths:
      - modules/
  system:
    paths:
      - system/