dist: trusty
language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install
  - printf "\n" | pecl install -f redis
  - printf "\n" | pecl install -f imagick
  - printf "\n" | pecl install -f memcached
  - printf "\n" | pecl install -f apcu

script:
  - vendor/bin/phpunit

after_success:
  - travis_retry vendor/bin/php-coveralls

notifications:
  email: false
